"""empty message

Revision ID: 57a00bbaa7ea
Revises: 8cc30a67749e
Create Date: 2022-05-22 11:07:36.517738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a00bbaa7ea'
down_revision = '8cc30a67749e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('up_id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['up_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('up_id', 'fan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
