"""empty message

Revision ID: 988e4d5d9874
Revises: d012b6521076
Create Date: 2022-02-09 20:25:37.428502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988e4d5d9874'
down_revision = 'd012b6521076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
