"""empty message

Revision ID: d012b6521076
Revises: cd3ce45912ca
Create Date: 2022-02-09 20:23:12.974762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd012b6521076'
down_revision = 'cd3ce45912ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('permission')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('permission', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
